lagou:
  message: 123
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.18.5:3306/batistest?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&characterSetResults=utf8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
